### ISSUE TITLE
"write" permission not allowed in list of values for "allow"

### ISSUE THREAD

**Issue by nnmrts** [jurassiscripts/velociraptor#48]
While trying to configure my module scripts, I stumbled upon a squiqqly orange warning underline in Visual Studio Code (using https://github.com/jurassiscripts/vscode-velociraptor) after adding `"write"` to the list of permissions under the key `"allow"` in my `scripts.json`:

<img width="359" alt="Bildschirmfoto 2021-03-27 um 10 42 43" src="https://user-images.githubusercontent.com/20396367/112716864-2be6c400-8ee9-11eb-94cc-f30a34080280.png">

Examining this further, it seems like the value `"write"` is not in the list of allowed values, even though it should be:

<img width="926" alt="Bildschirmfoto 2021-03-27 um 10 43 14" src="https://user-images.githubusercontent.com/20396367/112716877-3dc86700-8ee9-11eb-8dfb-30d0698ac409.png">

According to the [readme of velociraptor](https://github.com/jurassiscripts/velociraptor), the section [Permissions](https://github.com/jurassiscripts/velociraptor#permissions) states that Deno [permissions](https://deno.land/manual/getting_started/permissions) can be specified using the `allow` key, of which all but `"write"` can be specified without a warning.

I created this issue here because the vscode extension (at least at the moment) is only a "wrapper" around code in this repository and any fix there would actually be a fix here.

My suggestion would be to add `write?: string | boolean;` [here](https://github.com/jurassiscripts/velociraptor/blob/4914c231cf350e7d91aff30610d9b348762aebd4/src/scripts_config.ts#L195-L203) to the `AllowFlags` interface in [scripts_config.ts](https://github.com/jurassiscripts/velociraptor/blob/main/src/scripts_config.ts), for which I will add a PR shortly.

**Comment by umbopepato** [comment]
You're absolutely right @nnmrts, thank you so much for reporting and fixing this! 🙂

**Comment by jakenvac** [comment]
Hi, this is still an issue on the version of the types suggested in the docs [here](https://velociraptor.run/docs/vscode/)

**Comment by umbopepato** [comment]
@JakeHL you mean in the screenshot or in the manual type annotation? Version `v1.1.0` of the extension should show the write permission correctly

**Comment by jakenvac** [comment]
Sorry it wasn't very clear. I mean on the import statement here:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/9119973/174455367-c6115d5d-eb7a-4b0a-8c3c-12e62aaeba70.png">


I've created a PR for the docs project [here](https://github.com/jurassiscripts/velociraptor-dot-run/pull/5)

**Comment by umbopepato** [comment]
You're right! Actually some time ago I added a data provider that fetches the last vr version automatically at build time but I forgot to use it in this section. I fixed this while I was working on the dark theme, you should see the right version now! Thank you so much for the PR anyway 🙂

**Comment by jakenvac** [comment]
No worries, yours is a better solution. Thanks for updating, love the project.
