### ISSUE TITLE
VrCommand parses additional arguments

### ISSUE THREAD

**Issue by umbopepato** [jurassiscripts/velociraptor#70]
While the arguments are still forwarded correctly, their syntax is normalized to `--option [value]` (removing any `=` signs). These may cause unintended effects when forwarded to CLIs that require a particular syntax (see #69).

**Comment by umbopepato** [comment]
@c4spar I'm going to ask you a little help here: this happens when using `stopEarly()` while the `run` command (which uses `useRawArgs()`) works correctly. Is this an intended behavior? If yes, can the two modifiers be used together to accomplish this without having to manually register the `--help` and `--version` commands?

**Comment by c4spar** [comment]
@umbopepato i will look into it and check if i can pass non normalized arguments when using `stopEarly`.

**Comment by c4spar** [comment]
@umbopepato i fixed the bug in cliffy and made a PR to upgrade cliffy in velociraptor.

**Comment by umbopepato** [comment]
Awesome, thank you so much @c4spar! 😊
