### ISSUE TITLE
Support description for composite scripts

### ISSUE THREAD

**Issue by paambaati** [jurassiscripts/velociraptor#72]
Take this `script.yaml` for example –

```yaml
scripts:
  onething:
    desc: Do a simple thing
    cmd: echo "simple"
  manythings:
    - desc: Do some thing first
      cmd: echo "thing number 1"
    - desc: Do another thing next
      cmd: echo "thing number 2"
```

`vr` outputs this –

```
$ vr

  🦖 Available scripts

    • onething
    Do a simple thing
    $ echo "simple"

    • manythings
    $ echo "thing number 1", echo "thing number 2"
```

You'll notice that composite scripts don't have a description. I understand we can't have a top-level field for description because composite scripts are an array. Perhaps we could just print the descriptions of each script? Something like this –

```
$ vr

  🦖 Available scripts

    • onething
    Do a simple thing
    $ echo "simple"

    • manythings
    Do some thing first
    Do another thing next
    $ echo "thing number 1", echo "thing number 2"
```

**Comment by umbopepato** [comment]
@paambaati absolutely! Would you like to open a PR for this? 🙂

**Comment by paambaati** [comment]
@umbopepato BAM! https://github.com/jurassiscripts/velociraptor/pull/74

**Comment by umbopepato** [comment]
Thank you so much @paambaati, your changes are live in `1.1.0`! 😊 🎉
