### ISSUE TITLE
Broken after installing Deno v.1.13.0

### ISSUE THREAD

**Issue by sant123** [jurassiscripts/velociraptor#75]
Native plugins have been removed https://github.com/denoland/deno/pull/10908. 

So executing this command will raise an error:

`vr`

``` bash
error: Found argument '--allow-plugin' which wasn't expected, or isn't valid in this context
        Did you mean --allow-run?

USAGE:
    deno run <SCRIPT_ARG>... --allow-env=<allow-env> --allow-net=<allow-net> --allow-read=<allow-read> --allow-run=<allow-run> --allow-write=<allow-write>

For more information try --help
```

**Comment by paambaati** [comment]
@umbopepato @c4spar Will the fix be as simple as removing this line? If yes, I'd be happy to send a PR!

https://github.com/jurassiscripts/velociraptor/blob/cf8900575526d1b1f4b38f924bc82fa75f46484a/src/scripts_config.ts#L200

**Comment by umbopepato** [comment]
Hey @sant123, thanks for reporting!

Can you please specify what Deno version you're using? Also, does one of your scripts use the `plugin` permission? In that case running the single script would cause the error but the `vr` command alone should't trigger any `deno` command with the `plugin` permission...

@paambaati right, `AllowFlags` should be aligned to the new flags (remove `plugin` and add `ffi`). Your PR would be much appreciated 🙂

**Comment by sant123** [comment]
Hey @umbopepato, you can execute `vr` in any place, in any project, in any scripts file. It's totally broken since this update 😢

**Comment by sant123** [comment]
> @umbopepato @c4spar Will the fix be as simple as removing this line? If yes, I'd be happy to send a PR!
> 
> https://github.com/jurassiscripts/velociraptor/blob/cf8900575526d1b1f4b38f924bc82fa75f46484a/src/scripts_config.ts#L200

Definitely the `plugin` flag should be replaced by `ffi` flag.

**Comment by paambaati** [comment]
@umbopepato [`00fd1b1` (#76)](https://github.com/jurassiscripts/velociraptor/pull/76/commits/00fd1b1744c25fd9cc44ce43593d5926f05797b6) replaces the `plugin` flag with `ffi`.

**Comment by sant123** [comment]
Since this issue has been resolved and there's already a pull request to change allow-plugin for allow-ffi. I'm closing this one.

**Comment by sant123** [comment]
https://github.com/jurassiscripts/velociraptor/pull/76

**Comment by umbopepato** [comment]
Thank you so much @paambaati and sorry for the delay in merging your PR, your changes are now live in `1.2.0` 😊

**Comment by umbopepato** [comment]
The breaking change introduced in flags by `deno@^1.13.0` breaks Velociraptor installation files so a full re-install is required. 
This can be done either manually with the `-f` flag (see [Installation](https://velociraptor.run/docs/installation)) or by running vr in headless mode:

```shell
$ deno run -A https://code.velociraptor.run upgrade
```
