### ISSUE TITLE
`vr` command not found after installation

### ISSUE THREAD

**Issue by eklemen** [jurassiscripts/velociraptor#79]
Command I ran from https://velociraptor.run/docs/installation/ :
```
deno install -qAn vr https://deno.land/x/velociraptor@1.2.0/cli.ts
```

New terminal window in zsh
```
$ vr
zsh: command not found: vr
```

Tried to reinstall it by running command again (with -f flag) but get a module not found error
```
error: Cannot resolve module "file:///Users/<username>/pathtomyapp/vr".
```

MacOS Catalina 10.15.4
deno 1.13.1 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5

Let me know if there is any other information I can provide. Thanks!

**Comment by umbopepato** [comment]
@eklemen Have you [added](https://deno.land/manual@v1.13.2/tools/script_installer#:~:text=These%20must%20be%20added%20to%20the%20path%20manually%20if%20required) Deno's executable installation root to your `PATH`?

**Comment by eklemen** [comment]
This fixed it. My apologies!
