### ISSUE TITLE
GIT_ARGS NOT WORKING

### ISSUE THREAD

**Issue by jupegarnica** [jurassiscripts/velociraptor#82]
I believe GIT_ARGS env is not set properly.  Looks totally empty used at gitHook commit-msg

![image](https://user-images.githubusercontent.com/3143445/135631003-e1e59a79-648e-4566-80ce-5dbc588b3b31.png)

**Comment by jupegarnica** [comment]
I am working on ubuntu 21.04, and zsh-. but also happens in bash and sh.

**Comment by umbopepato** [comment]
Hi @jupegarnica!
What version of Velociraptor are you using?

**Comment by jupegarnica** [comment]
and deno 1.14.0

**Comment by umbopepato** [comment]
Can you please try and set the `VR_LOG` env variable to `"DEBUG"` and share the output of the commitlint hook script?

**Comment by jupegarnica** [comment]
@umbopepato sure!,  here it is:

![image](https://user-images.githubusercontent.com/3143445/135709096-8706ac30-f0e3-424c-ae95-535c2729b6dd.png)

hope is useful

**Comment by umbopepato** [comment]
Ok so it looks like the `GIT_ARGS` variable is properly set. What about
```shell
$ cat .git/hooks/commit-msg
```
?

**Comment by jupegarnica** [comment]
@umbopepato do you mean this?

![image](https://user-images.githubusercontent.com/3143445/135709638-bd249797-2a85-4ac8-ad1a-f4cf1266553e.png)
