### ISSUE TITLE
 there is any way to pass data between githooks scripts?

### ISSUE THREAD

**Issue by jupegarnica** [jurassiscripts/velociraptor#83]
I am trying  to source env variables without success.

![image](https://user-images.githubusercontent.com/3143445/135647817-e8147eeb-3442-4aa2-a36d-e40f7b804f1e.png)

**Comment by umbopepato** [comment]
@jupegarnica if I'm not wrong this doesn't work because the two hooks run in different (not nested) shells, where the `export`ed variables are not shared. What you can do is call the `getStagedFiles.sh` script from both hooks to avoid repeating the logic.

**Comment by jupegarnica** [comment]
Make sense,

Thanks
